// Centralized company types definition used across the application
export const COMPANY_TYPES = [
  "Healthcare Services",
  "Eldercare Facility",
  "Hospital & Medical Centers",
  "Nursing Homes",
  "Assisted Living",
  "Mental Health Services",
  "Food Processing",
  "Food & Beverage",
  "Restaurant & Hospitality",
  "Software Development",
  "IT Solutions",
  "IT Consulting",
  "IT Services",
  "Web Development",
  "Mobile App Development",
  "Cloud Services",
  "Cybersecurity",
  "Data Analytics",
  "AI & Machine Learning",
  "DevOps & Infrastructure",
  "SaaS & Technology",
  "Manufacturing",
  "Automotive",
  "Pharmaceuticals",
  "Retail",
  "E-commerce",
  "Education",
  "Higher Education",
  "K-12 Education",
  "Training & Development",
  "Financial Services",
  "Banking",
  "Insurance",
  "Real Estate",
  "Legal Services",
  "Construction",
  "Architecture & Engineering",
  "Transportation",
  "Logistics & Supply Chain",
  "Energy & Utilities",
  "Telecommunications",
  "Media & Entertainment",
  "Marketing & Advertising",
  "Business Consulting",
  "Management Consulting",
  "HR Consulting",
  "Non-Profit",
  "Government",
  "Public Sector",
  "Agriculture",
  "Environmental Services",
  "Other"
] as const;

export type CompanyType = typeof COMPANY_TYPES[number];